# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0f586c91fcf3ec663891d732e8287cce8480cdcf01cdbe41a4cd5636e637da8250c1fc600f433650bdf359b69967797c9b54c802ef3d39e7eb15dbaf9070342

test:
  secret_key_base: 45c00002bab8a15c420b489d343748c3813d9e01ac12b2935bf2234f5f46932a64610147266e70f0deca4917f9211636f418e28f098fda8e422f26ba24e2d706

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
